[build]
    base = "new-work/"
    publish = "public/"

[[plugins]]
    package = "@netlify/plugin-emails"

[[plugins]]
    package = "@netlify/plugin-gatsby"

[functions.emails]
    included_files = ["emails/**"]