# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - dependencies
    schedule:
      interval: 'weekly'
    groups:
      gatsby:
        patterns:
          - 'gatsby*'
      visx:
        patterns:
          - '@visx*'
      react:
        patterns:
          - 'react*'
      retext:
        patterns:
          - 'retext*'
