name: '[eLearning] Check links'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: --verbose --no-progress --insecure --exclude="/.+(ctbto.org).+/" --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" './e-learning/content/**/*.mdx'
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Fix broken links
          content-filepath: ./lychee/out.md
          labels: E-Learning
