name: '[eLearning] Update Treaties'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'
permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Run update script
        run: ${GITHUB_WORKSPACE}/scripts/updateTreaties.sh
        env:
          BRANCH_NAME: update-treaty-participants
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
