name: '[New Work] Check Markdown Links'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lycheeverse/lychee-action@v1.5.4
        id: lychee
        with:
          args: --verbose --no-progress --insecure './new-work/content/**/*.mdx'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-issue-from-file@v4
        if: env.lychee_exit_code != 0
        with:
          title: Fix broken links
          content-filepath: ./lychee/out.md
          labels: 'New Work'
