name: Update Treaty Participants

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 1 * *' # 7:00 on the first of every month

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          path: updates
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            main/package-lock.json
            updates/package-lock.json
      - name: Run update script
        run: ${GITHUB_WORKSPACE}/main/scripts/updateTreaties.sh
        env:
          BRANCH_NAME: update-treaty-participants
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
